<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTicketNumber($visitDate){
        $qb = $this
            ->createQueryBuilder('res')
            ->innerJoin('res.tickets', 'bil','WITH', 'res.visitDate = :visitDate')
            ->select('COUNT(bil)')
            ->setParameter('visitDate',$visitDate)
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
