<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNombreBillet($jourVisiste){
        $qb = $this
            ->createQueryBuilder('r')
            ->innerJoin('r.billet', 'b')
            ->addSelect('b')
        ;
    }
}
