<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNombreBillet($jourVisiste){
        $qb = $this
            ->createQueryBuilder('res')
            ->innerJoin('res.billets', 'bil','WITH', 'res.jourVisite = :jourVisite')
            ->select('COUNT(bil)')
            ->setParameter('jourVisite',$jourVisiste)
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
