app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
         _locale: en|fr

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /fr/
        permanent: true